ITEM.baseItem = "weapon_base"
ITEM.name = "M40A1"
ITEM.PrintName = "#Item_WeaponM40a1_PrintName"
ITEM.cost = 0
ITEM.model = "models/items/m40a1.mdl"
ITEM.weight = 4.8
ITEM.access = "V"
ITEM.classes = {CLASS_EOW}
ITEM.weaponClass = "sxbase_m40a1"
ITEM.business = true
ITEM.description = "#Item_WeaponM40a1_Description"
ITEM.isAttachment = true
ITEM.loweredOrigin = Vector(3, 0, -4)
ITEM.loweredAngles = Angle(0, 45, 0)
ITEM.attachmentBone = "ValveBiped.Bip01_Spine2"
ITEM.attachmentOffsetAngles = Angle(150, -2, 95)
ITEM.attachmentOffsetVector = Vector(-3, 5, 1)
