ITEM.baseItem = "weapon_base"
ITEM.name = "M9 Beretta"
ITEM.PrintName = "#Item_WeaponM9_PrintName"
ITEM.cost = 0
ITEM.model = "models/weapons/w_m9beretta.mdl"
ITEM.weight = 1
ITEM.access = "V"
ITEM.classes = {CLASS_EOW}
ITEM.weaponClass = "sxbase_m9"
ITEM.business = true
ITEM.description = "#Item_WeaponM9_Description"
ITEM.isAttachment = true
ITEM.loweredOrigin = Vector(3, 0, -4)
ITEM.loweredAngles = Angle(0, 45, 0)
ITEM.attachmentBone = "ValveBiped.Bip01_Pelvis"
ITEM.attachmentOffsetAngles = Angle(-180, 180, 90)
ITEM.attachmentOffsetVector = Vector(-4.19, 0, -8.54)
